### ISSUE TITLE
Update Node version on Dockerfile

### ISSUE THREAD

**Issue by diogo405** [njivaolafpro/invoice-management-sample#1]
Currently, it's version 8.11 https://github.com/njivaolafpro/invoice-management-sample/blob/main/Dockerfile#L1
Don't you wanna update to 16?!

**Comment by njivaolafpro** [comment]
Indeed 👀thanks. 
That was effectively a miss ^^ LTS should be used so v16 ^^

**Comment by njivaolafpro** [comment]
Fixed :)
